# import time
# now=time.time()
# print("当前时间戳是：%f"%now)
# import time
# print("当前时间",time.localtime())
# print("0时间对应的时间戳：",time.localtime())
# import time
# t=(2018,7,17,17,3,1,1,1,0)
# secs=time.mktime(t)
# print("time.mktime(t) %f"%secs)
# print("time.mktime:%f"%time.mktime(time.localtime(secs)))
# import time
# print("time.gmtime():",time.gmtime())
# print("time.gmtime(0):",time.gmtime(0))
import time
# t=(2018,7,17,17,3,1,1,1,0)
# print("time.astime(t)",time.asctime(t))
# print("time.asctime(time.localtime()",time.asctime(time.localtime()))
# import time
# print("time.ctime():%s"%time.ctime())
# print("time.ctime(0):%s"%time.ctime(0))
# import time
# print("Start:%s"%time.ctime())
# time.sleep(9)
# print("End:%s"%time.ctime())
# import time
# t=(2018,7,17,17,3,1,1,1,0)
# t=time.mktime(t)
# print(time.strftime("%b %d %Y %H:%M:%S",time.gmtime(t)))
# import time
# struct_time=time.strptime("Jul 17 2018 09:03:01","%b %d %Y %H:%M:%S")
# print("返回元组",struct_time)
# import datetime
# date=datetime.date(2018,7,1)
# print(date)
# today=datetime.date.today()
# print(today)
# print(today.weekday())
# print(date.isoformat())
# print(date.strftime("%Y-%m-%d"))
# print(date.strftime("%y-%b-%d"))
# time1=datetime.time()
# print(time1)
# time2=datetime.time(hour=8,second=7)
# print(time2)
# print(datetime.time.min)
# print(datetime.time.max)
# print(time2.isoformat())
# time3=datetime.time(hour=16,second=7,microsecond=123)
# print(time3.strftime("%H:%M:%S"))
# print(time3.strftime("%p %I:%M:%S:%f"))
# dt=datetime.datetime(year=2018,month=7,day=1,hour=16,second=10)
# print(dt)
# today=datetime.datetime.today()
# print(today)
# now=datetime.datetime.now()
# print(now)
# now=datetime.datetime.utcnow()
# print(now)
# import time
# t1=datetime.datetime.fromtimestamp(time.time()-86400)
# print(t1)
# now=datetime.datetime.now()
# print(now.date())
# print(now.time())
# date=datetime.date(2018,7,1)
# time=datetime.time(8,12,4)
# dt=datetime.datetime.combine(date,time)
# print(dt)
# dt1=datetime.datetime(2018,7,1,15,16,10)
# dt2=dt1+datetime.timedelta(weeks=-2)
# print(dt1)
# print(dt2)
# print(dt1-dt2)
# print(dt2-dt1)
# china=datetime.timezone(datetime.timedelta(hours=8))
# utc=datetime.timezone(datetime.timedelta(hours=0))
# chinat=datetime.datetime.now(china)
# utct=datetime.datetime.now(utc)
# print(chinat)
# print(utct)
import calendar
# print(calendar.isleap(2000))
# print(calendar.isleap(2018))
# for i in range(1500,2021):
#     if calendar.isleap(i):
#         print(i)
# print(calendar.leapdays(1990,2021))
# print(calendar.leapdays(2017,2050))
# print(calendar.month(2021,7))
# print(calendar.month(2021,7,w=3))
# print(calendar.month(2021,7,l=3))
# print(calendar.monthcalendar(2021,7))
# print(calendar.monthrange(2021,7))
# print(calendar.weekday(2021,7,1))
# print(calendar.calendar(2021))
