name_set=set()
name_set.add('Jenny')
name_set.add('Ellena')
name_set.add('Alice')
name_set.add('Candy')
name_set.add('David')
name_set.add('Hally')
name_set.add('Bob')
name_set.add('Isen')
name_set.add('Karl')
print(name_set)
name_set2=set()
new_name=['Jenny', 'Ellena', 'Alice', 'Candy', 'David', 'Hally', 'Bob', 'Isen', 'Karl']
name_set2.update(new_name)
print(name_set2)