# Generated by Django 3.2.5 on 2021-08-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='summary',
            new_name='sumary',
        ),
        migrations.AddField(
            model_name='article',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
