print('I\'m fine')
print("""How are you\nfuck you man
wo defuck""")
print(3*'am'+'your father')
print('liyaohua'+'eer')
word='python'
print(word[0])
print('text')
a=10
b=10
print(a*b)
print(word[:])
print(word[1:2])
print(word[-6:1])
print(word[-6:4])
print(word[-1:6])
print('J'+word[1:])
c=len(word)#长度
print(c)
square=[1,1,2,3,4,6]
print(square)
print(square[-3:])
print(square[2])
print(1==2)
print(1==1)
print(a/b/c)
print(a**b)
d=10;
e=7;
print(d%e)
print(d//e)
f=100.0
f%=10
print(f)
m=9
n=13
print(m&n)#按位与，都是1为1，否则为0
print(m|n)#按位或，都是0为0，否则为1
print(m^n)#按位异或，相同为0，否则为1
print(~a)#按位取反
print(a<<2)#左移右操作数个位数
print(b>>2)#右移右操作数个位数
if a==b: print(a)
print(5 in (1,2,3,4,5,6))#判断在里面
print(a is b)#a是否为b
#列表
x1=[1,2,3,4]
print("列表")
print(x1[0])
print(x1[1])
print("-----------")
#元组
x2=(1,2,3,4)
print("元组")
print(x2[0])
print(x2[1])
print(x1[-1])
print(x1[-2])
print(x2[-1])
print(x2[-2])
print(x1[0:3])
print(x1[0:2])
print(x2[0:3])
print(x2[1:2])
print(x2[3:4])
print(x2[4:5])
print("----------")
print(x2[:3])
print(x2[3:])
print("字符串------------")
x3="abcd"
print(x3[0:2])
print(x3[4:5])
print(x3[3:4])
print("=-=-=--=-=--==-=--=")
x4=[1,2,3,4,5,6,7,8]
x5=(1,2,3,4,5,6,7,8)
x6="12345678"
#列表
print("\n列表")
print(x4[1:5])
print(x4[1:5:1])
print(x4[1::2])
print(x4[1::3])
print(x4[5::-1])
print(x4[5::-2])
#元组
print("\n元组")
print(x5[1:5])
print(x5[1:5:1])
print(x5[1::2])
print(x5[1::3])
print(x5[5::-1])
print(x5[5::-2])
#字符串
print("\n字符串")
print(x6[1:5])
print(x6[1:5:1])
print(x6[1::2])
print(x6[1::3])
print(x6[5::-1])
print(x6[5::-2])
#序列相加
print("\n列表")
x1=[1,2,3]+[4,5,6]
print(x1)
print("\n元组")
x2=(1,2,3)+(4,5,6)
print(x2)
print("\n字符串")
x3="123"+"456"
print(x3)
#序列重复
print("\n列表")
x1=[1,2,3]*5
print(x1)
print("\n元组")
x2=(1,2,3)*5
print(x2)
print("\n字符串")
x3="123"*5
print(x3)
#长度，最小值，最大值，求和
print("\n列表")
x1=[1,2,3,4,5,6]
print("长度",len(x1))
print("最小值",min(x1))
print("最大值",max(x1))
print("求和",sum(x1))
print("\n元组")
x2=(1,2,3,4,5,6)
print("长度",len(x2))
print("最小值",min(x2))
print("最大值",max(x2))
print("求和",sum(x2))
print("\n字符串")
x3="123456"
print("长度",len(x3))
print("最小值",min(x3))
print("最大值",max(x3))
#列表
print("\n列表---------------")
print("\n列表更新")
l1=[1,2,3,4,5,6]
print(l1)
l1[2]="管大爷"
print(l1)
l1[2]=0
print(l1)
print("\n列表增加元素")
#append
l1.append("hello")
print(l1)
#extend
l1=[1,2,3,4,5,6]
l1.append([7,8])
print("append\n",l1)
l2=[1,2,3,4,5,6]
l2.extend([7,8])
print("extend\n",l2)
#insert
l2.insert(2,"管大爷")
print("insert\n",l2)
#删除元素
l1=[1,2,3,4,5,6]
l1.pop()
print("pop\n",l1)
r2=l1.pop(2)#删除指定位置
print(r2)
print(l1)
#remove
l1=["gdy","lxy","jzc","lyh"]
l1.remove("gdy")
print("remove\n",l1)
#del
del l1[1]
print(l1)
#index
l1=["gdy","lxy","jzc","lyh"]
print("gdy在",l1.index("gdy"))
print("jzc在",l1.index("jzc"))
#reverse
l1.reverse()
print("reverse\n",l1)
#count
l2=[1,2,3,4,5,6,7,7,7,8]
print("count\n",l2.count(7))
#sort
l3=[4,32,1,5,1,67,21,5]
l3.sort()
print("sort\n",l3)
#元组能用index,count,不能修改，要删全部删完用del l1
#字典
english={
    "we":"我们",
    "world":"世界",
    "happy":"快乐",
}
print(english,type(english))
print("world",english["world"])
english["world"]="城市"
print(english)
#删除
del english["world"]
print(english)
#复制字典
#直接等会改变原来的字典
#用copy则不会
english1={
"we":"我们",
    "world":"世界",
    "happy":"快乐",
}
english2=english1
english3=english.copy()
print("english1",english1)
print("english2",english2)
print("english3",english3)
print("---------------")
print("改变english2")
english2["city"]="城市"
print("english1",english1)
print("english2",english2)
print("english3",english3)
print("------------------")
print("改变english3")
english3["shcool"]="学校"
print("english1",english1)
print("english2",english2)
print("english3",english3)
#fromkeys创建一个新字典，用序列中的元素作字典的键，第二个参数为对应的初始值
seq=("name","age","class")
students=dict.fromkeys(seq)
print("不指定默认值",students)
student2=dict.fromkeys(seq,15)
print("指定默认值",student2)
#get方法返回键对应的值，如果不存在就返回默认值
print("world",english1.get("world"))
print("city1",english1.get("city1"))
print("city1",english1.get("city1","giao华"))
#keys返回字典中所有的键,还能配合in组合使用
print(english1.keys())
print("是否存在giao华？","giao华" in english1.keys())
#value返回字典中所有值
print("english中所有的值：",english1.values())
#items返回所有键和值
print(english1.items())
for k,v in english1.items():
    print(k,"=>",v)
#set集合
empty=set()
print("空集合",empty)
number={1,2,3}
print("数字集合",number)
mix=set([1,"您好",3.14])
print("混合集和",mix)
#add添加元素
number={1,2,3}
print(number)
number.add(5)
print(number)
number.add(2)
print(number)
#remove删除元素
number1={1,2,3,4,5,6}
print(number1)
number1.remove(3)
print(number1)
number1.remove(6)
print(number1)
#集合操作
n1={1,3,5}
n2={2,7,1,3}
print("n1",n1)
print("nm2",n2)
print("交集",n1&n2)
print("并集",n1|n2)
print("差集",n1-n2)
print("对称差集",n1^n2)#交集以外的所有元素
l1=[x for x in range(5)]
print(l1)
l2=[x for x in range(10) if x%2!=0]
print(l2)
d1={n:n**2 for n in range(5)}
print(d1)
d2={v:k for k,v in d1.items()}
print(d2)

